# configs/model/eegpt/variants.yaml
variants:
  tiny1:
    embed_dim: 64
    embed_num: 1
    encoder_depth: 2
    predictor_depth: 2
    reconstructor_depth: 4
    num_heads: 4

  tiny2:
    embed_dim: 128
    embed_num: 4
    encoder_depth: 4
    predictor_depth: 4
    reconstructor_depth: 4
    num_heads: 4
    
  base1:
    embed_dim: 256
    embed_num: 1
    encoder_depth: 6
    predictor_depth: 6
    reconstructor_depth: 6
    num_heads: 4
    gpt_num_hidden_layers: 6
    
  large:
    embed_dim: 512
    embed_num: 4
    encoder_depth: 8
    predictor_depth: 8
    reconstructor_depth: 8
    num_heads: 8
    gpt_num_hidden_layers: 10
    gpt_num_attention_heads: 16
    
  L_822:
    embed_dim: 512
    embed_num: 4
    encoder_depth: 8
    predictor_depth: 2
    reconstructor_depth: 2
    num_heads: 8

gpt_default:
  embed_dim: 768
  num_hidden_layers_embedding_model: 2
  num_hidden_layers: 4
  num_attention_heads: 12
  intermediate_dim_factor: 4
  hidden_activation: gelu_new
  dropout: 0.1
  num_hidden_layers_unembedding_model: 2

order_default:
  num_layers: 2
  num_heads: 8