# configs/hydra/default.yaml
run:
  # Tự động tạo thư mục: outputs/tên_dataset/tên_model/ngày/giờ
  dir: outputs/${dataset.name}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: multirun/${dataset.name}/${model.name}/${now:%Y-%m-%d_%H-%M-%S}