# configs/hydra/downstream.yaml
run:
  # Tự động tạo thư mục: outputs/tên_dataset/tên_model/ngày/giờ
  dir: outputs_downstream/${hydra:runtime.choices.model}/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: multirun_downstream/${hydra:runtime.choices.model}/${now:%Y-%m-%d_%H-%M-%S}