name: bciciv2a
num_classes: 4
num_channels: 22
use_chans_num : 15
time_points : 1024
use_channels_names:
    - FP1
    - FP2
    - F7
    - F3
    - FZ
    - F4
    - F8
    # - T7
    - C3
    - CZ
    - C4
    # - T8
    # - P7
    - P3
    - PZ
    - P4
    # - P8
    - O1
    - O2
datasets_dir: /home/infres/ttran-25/project/datasets/downstream/lmdb_bciciv2a_0_38Hz/LOSO_A01