# configs/config.yaml
defaults:
  - _self_
  - dataset: pretraining_lmdb/v1
  - model: cbramod/pretrain
  - tasks: reconstruction_only  # hoặc reconstruction_only, contrastive_only
  - weight_method: linear
  - hydra: pretrain

seed: 42
module:
  name: cbramod_pretrain_module

data:
  batch_size: 64
  num_workers: 4
  patch_size: 200

trainer:
  max_epochs: 20
  accelerator: auto
  devices: 1
  precision: 32

optimizer:
  name: adamw
  # lr: 6e-5
  weight_decay: 0.01

scheduler:
  name: cosine