defaults:
  - _self_
  - dataset: pretraining_lmdb/v1
  - model: eegpt/pretrain
  - tasks: both
  - weight_method: famo
  - module: eegpt_pretrain_module
  - hydra: pretrain

seed: 42

# Model configuration
# model:
#   variant: large  # Dễ dàng thay đổi variant
#   img_size: [19, 3200]
#   patch_size: 64

# Training
data:
  batch_size: 64
  num_workers: 8
  scale_div: 100.0
  augment_prob: 0.25
  mask_ratio: 0.4

trainer:
  max_epochs: 100 # set to 5 for debugging, defaults is 100
  accelerator: auto
  devices: 1
  precision: 32
  # accumulate_grad_batches: 4 # to solve memory problem when batch_size is too large
  # gradient_clip_val: 1.0
  # gradient_clip_algorithm: norm

optimizer:
  name: adamw
  lr: 0.0001
  weight_decay: 0.01

scheduler:
  name: cosine

# Logging
# logging:
#   log_root: ./logs
#   auto_name: true  # Tự động generate tên experiment